FROM alpine:3.19

ARG APP_VERSION

RUN set -ex; \
    apk add --no-cache \
        bzip2 \
        curl \
        gnupg \
        shadow \
        rsync \
        ffmpeg \
        imagemagick \
        imagemagick-heic \
        imagemagick-jpeg \
        imagemagick-svg \
        imagemagick-tiff \
        imagemagick-webp \
        php82 \
        php82-fpm \
        php82-bcmath \
        php82-bz2 \
        php82-ctype \
        php82-curl \
        php82-dom \
        php82-exif \
        php82-fileinfo \
        php82-gd \
        php82-gmp \
        php82-iconv \
        php82-intl \
        php82-mbstring \
        php82-opcache \
        php82-openssl \
        php82-pcntl \
        php82-pdo_pgsql \
        php82-posix \
        php82-session \
        php82-simplexml \
        php82-sysvsem \
        php82-xml \
        php82-xmlreader \
        php82-xmlwriter \
        php82-zip \
        php82-pecl-apcu \
        php82-pecl-memcached \
        php82-pecl-imagick \
        php82-pecl-redis; \
    ln -sf /usr/bin/php82 /usr/bin/php

RUN set -ex; \
    mkdir -p /var/www/html; \
    groupmod -g 101 www-data; \
    adduser -h /var/www/html -H -s /sbin/nologin -S -u 101 -G www-data www-data

WORKDIR /var/www/html

# set recommended PHP.ini settings
# see https://docs.nextcloud.com/server/stable/admin_manual/installation/server_tuning.html#enable-php-opcache
ENV PHP_MEMORY_LIMIT=512M
ENV PHP_UPLOAD_LIMIT=1024M
COPY php.conf.d/ /etc/php82/conf.d/
COPY php-fpm.d/ /etc/php82/php-fpm.d/
RUN rm /var/spool/cron/crontabs/root; \
    echo '*/5 * * * * php82 -f /var/www/html/cron.php' > /var/spool/cron/crontabs/www-data; \
    \
    chown -R www-data:www-data /var/www; \
    chmod -R g=u /var/www

ENV NEXTCLOUD_VERSION=${APP_VERSION}

RUN set -ex; \
    curl -fsSL -o nextcloud.tar.bz2 \
        "https://download.nextcloud.com/server/releases/nextcloud-${NEXTCLOUD_VERSION}.tar.bz2"; \
    curl -fsSL -o nextcloud.tar.bz2.asc \
        "https://download.nextcloud.com/server/releases/nextcloud-${NEXTCLOUD_VERSION}.tar.bz2.asc"; \
    export GNUPGHOME="$(mktemp -d)"; \
    # gpg key from https://nextcloud.com/nextcloud.asc
    gpg --batch --keyserver keyserver.ubuntu.com  --recv-keys 28806A878AE423A28372792ED75899B9A724937A; \
    gpg --batch --verify nextcloud.tar.bz2.asc nextcloud.tar.bz2; \
    mkdir -p /usr/src; \
    tar -xjf nextcloud.tar.bz2 -C /usr/src/; \
    gpgconf --kill all; \
    rm nextcloud.tar.bz2.asc nextcloud.tar.bz2; \
    rm -rf "$GNUPGHOME" /usr/src/nextcloud/updater; \
    mkdir -p /usr/src/nextcloud/data; \
    mkdir -p /usr/src/nextcloud/custom_apps; \
    chmod +x /usr/src/nextcloud/occ;

COPY entrypoint.sh upgrade.sh upgrade.exclude /
COPY config/* /usr/src/nextcloud/config/

VOLUME /var/www/html

ENTRYPOINT ["/entrypoint.sh"]
CMD ["php-fpm82", "-F"]
